openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts app
  license:
    name: ISC
    identifier: ISC
  description: This is a documentation of contacts app
tags:
  - name: Contacts
    description: Contacts operations.
  - name: Auth
    description: Auth operations.
servers:
  - url: http://localhost:3000
  - url: https://contacts-app-jp8q.onrender.com
paths:
  /contacts:
    get:
      $ref: ../swagger/paths/get.yaml
    post:
      $ref: ../swagger/paths/post.yaml
  /contacts/{id}:
    get:
      $ref: ../swagger/paths/{id}/get.yaml
    patch:
      $ref: ../swagger/paths/{id}/patch.yaml
    delete:
      $ref: ../swagger/paths/{id}/delete.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
